id: P9020B554
initial_creation_type: input
source_metadata:
  title: Tsangpa Gyare Yeshe Dorje
  language: bo
  description: 'Texts by and about Tsangpa Gyare Yeshe Dorje (gtsang pa rgya ras ye
    shes rdo rje, 1161–1211), the founder of Druk Monastery:'
  volume:
    9819218642cf43feb89dffcdd4e8b886:
      title: The Fourfold 'Manam' Refuge
      parent: Prayers
created_at: '2022-03-01T01:54:13.256713'
last_modified_at: '2022-03-01T01:54:13.256715'
statistics:
  total_words: 115
  total_non_words: 11
quality:
  non_words_ratio: 0.1
